apiVersion: v1
kind: PersistentVolume
metadata:
  name: project-data-0001
  namespace: project-management
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /tmp/project-data-0001
    type: DirectoryOrCreate

